<?php


abstract class ConfigurationName {
	const ORGANIZATION_TYPE =    'ORGANIZATION_TYPE';
	const REQUEST_FORM_DUPLIC_EDU =    'REQUEST_FORM_DUPLIC_EDU';
	const REQUEST_FORM_EXTERN_STUDY =    'REQUEST_FORM_EXTERN_STUDY';
	const REQUEST_FORM_CHILDREN_PROPERTY =    'REQUEST_FORM_CHILDREN_PROPERTY';
	const REQUEST_FORM_CHILDREN_ADOPTION =    'REQUEST_FORM_CHILDREN_ADOPTION';
	const REQUEST_FORM_CHILDREN_DISPOSABLE =    'REQUEST_FORM_CHILDREN_DISPOSABLE';
	const REQUEST_FORM_PAYMENT_FAMILY =    'REQUEST_FORM_PAYMENT_FAMILY';
	const REQUEST_FORM_CHILDREN_TURN =    'REQUEST_FORM_CHILDREN_TURN';
	const REQUEST_FORM_ACADEM_MOBILE =    'REQUEST_FORM_ACADEM_MOBILE';
	const REQUEST_FORM_GRADUATE_ADMISSION =    'REQUEST_FORM_GRADUATE_ADMISSION';
	const REQUEST_FORM_COLLEGE =    'REQUEST_FORM_COLLEGE';
	const REQUEST_FORM_PMPK =    'REQUEST_FORM_PMPK';
	const REQUEST_FORM_ATTESTATION_TEACHER =    'REQUEST_FORM_ATTESTATION_TEACHER';
	const REQUEST_FORM_UNIVERSITY_ADMISSION =    'REQUEST_FORM_UNIVERSITY_ADMISSION';
	const REQUEST_FORM_DOC_ACCEPTANCE_DDO =    'REQUEST_FORM_DOC_ACCEPTANCE_DDO';
	const REQUEST_FORM_DOC_QUEVED_DDO =    'REQUEST_FORM_DOC_QUEVED_DDO';
	const REQUEST_FORM_ACCEPT_DOC_EDU =    'REQUEST_FORM_ACCEPT_DOC_EDU';
	const REQUEST_FORM_GOVERNMENT_ORDER =    'REQUEST_FORM_GOVERNMENT_ORDER';
	const REQUEST_FORM_CONTEST_LEADERS =    'REQUEST_FORM_CONTEST_LEADERS';
	const REQUEST_FORM_RECOGNITION_EDUCATION =    'REQUEST_FORM_RECOGNITION_EDUCATION';
	const REQUEST_FORM_PAYMENT_CARE_DEFINE =    'REQUEST_FORM_PAYMENT_CARE_DEFINE';
	const REQUEST_FORM_PROGRAM_BOLASHAK =    'REQUEST_FORM_PROGRAM_BOLASHAK';
	const REQUEST_FORM_REALESTATE_BOLASHAK =    'REQUEST_FORM_REALESTATE_BOLASHAK';
	const REQUEST_FORM_STATUS_BOLASHAK =    'REQUEST_FORM_STATUS_BOLASHAK';
	const REQUEST_FORM_LETTER_GUARANTEE =    'REQUEST_FORM_LETTER_GUARANTEE';
	const REQUEST_FORM_ADVANCE_PAYMENT =    'REQUEST_FORM_ADVANCE_PAYMENT';
	const REQUEST_FORM_INTERNATIONAL_EDU =    'REQUEST_FORM_INTERNATIONAL_EDU';
}

